#pragma once

using namespace std;

map<RE::ActorValue, RE::BSFixedString> ACTOR_VALUES = {
	{ RE::ActorValue::kNone, "None" },
	{ RE::ActorValue::kAggresion, "Aggression" },
	{ RE::ActorValue::kConfidence, "Confidence" },
	{ RE::ActorValue::kEnergy, "Energy" },
	{ RE::ActorValue::kMorality, "Morality" },
	{ RE::ActorValue::kMood, "Mood" },
	{ RE::ActorValue::kAssistance, "Assistance" },
	{ RE::ActorValue::kOneHanded, "OneHanded" },
	{ RE::ActorValue::kTwoHanded, "TwoHanded" },
	{ RE::ActorValue::kArchery, "Marksman" },
	{ RE::ActorValue::kBlock, "Block" },
	{ RE::ActorValue::kSmithing, "Smithing" },
	{ RE::ActorValue::kHeavyArmor, "HeavyArmor" },
	{ RE::ActorValue::kLightArmor, "LightArmor" },
	{ RE::ActorValue::kPickpocket, "Pickpocket" },
	{ RE::ActorValue::kLockpicking, "Lockpicking" },
	{ RE::ActorValue::kSneak, "Sneak" },
	{ RE::ActorValue::kAlchemy, "Alchemy" },
	{ RE::ActorValue::kSpeech, "Speechcraft" },
	{ RE::ActorValue::kAlteration, "Alteration" },
	{ RE::ActorValue::kConjuration, "Conjuration" },
	{ RE::ActorValue::kDestruction, "Destruction" },
	{ RE::ActorValue::kIllusion, "Illusion" },
	{ RE::ActorValue::kRestoration, "Restoration" },
	{ RE::ActorValue::kEnchanting, "Enchanting" },
	{ RE::ActorValue::kHealth, "Health" },
	{ RE::ActorValue::kMagicka, "Magicka" },
	{ RE::ActorValue::kStamina, "Stamina" },
	{ RE::ActorValue::kHealRate, "HealRate" },
	{ RE::ActorValue::KStaminaRate, "StaminaRate" },
	{ RE::ActorValue::kSpeedMult, "SpeedMult" },
	{ RE::ActorValue::kInventoryWeight, "InventoryWeight" },
	{ RE::ActorValue::kCarryWeight, "CarryWeight" },
	{ RE::ActorValue::kCriticalChance, "CriticalChance" },
	{ RE::ActorValue::kMeleeDamage, "MeleeDamage" },
	{ RE::ActorValue::kUnarmedDamage, "UnarmedDamage" },
	{ RE::ActorValue::kMass, "Mass" },
	{ RE::ActorValue::kVoicePoints, "VoicePoints" },
	{ RE::ActorValue::kVoiceRate, "VoiceRate" },
	{ RE::ActorValue::kDamageResist, "DamageResist" },
	{ RE::ActorValue::kPoisonResist, "PoisonResist" },
	{ RE::ActorValue::kResistFire, "ResistFire" },
	{ RE::ActorValue::kResistShock, "ResistShock" },
	{ RE::ActorValue::kResistFrost, "ResistFrost" },
	{ RE::ActorValue::kResistMagic, "ResistMagic" },
	{ RE::ActorValue::kResistDisease, "ResistDisease" },
	{ RE::ActorValue::kUnknown46, "PerceptionCondition" },
	{ RE::ActorValue::kUnknown47, "EnduranceCondition" },
	{ RE::ActorValue::kUnknown48, "LeftAttackCondition" },
	{ RE::ActorValue::kUnknown49, "RightAttackCondition" },
	{ RE::ActorValue::kUnknown50, "LeftMobilityCondition" },
	{ RE::ActorValue::kUnknown51, "RightMobilityCondition" },
	{ RE::ActorValue::kUnknown52, "BrainCondition" },
	{ RE::ActorValue::kParalysis, "Paralysis" },
	{ RE::ActorValue::kInvisibility, "Invisibility" },
	{ RE::ActorValue::kNightEye, "NightEye" },
	{ RE::ActorValue::kDetectLifeRange, "DetectLifeRange" },
	{ RE::ActorValue::kWaterBreathing, "WaterBreathing" },
	{ RE::ActorValue::kWaterWalking, "WaterWalking" },
	{ RE::ActorValue::kUnknown59, "Unknown59" },
	{ RE::ActorValue::kFame, "Fame" },
	{ RE::ActorValue::kInfamy, "Infamy" },
	{ RE::ActorValue::kJumpingBonus, "JumpingBonus" },
	{ RE::ActorValue::kWardPower, "WardPower" },
	{ RE::ActorValue::kRightItemCharge, "RightItemCharge" },
	{ RE::ActorValue::kArmorPerks, "ArmorPerks" },
	{ RE::ActorValue::kShieldPerks, "ShieldPerks" },
	{ RE::ActorValue::kWardDeflection, "WardDeflection" },
	{ RE::ActorValue::kVariable01, "Variable01" },
	{ RE::ActorValue::kVariable02, "Variable02" },
	{ RE::ActorValue::kVariable03, "Variable03" },
	{ RE::ActorValue::kVariable04, "Variable04" },
	{ RE::ActorValue::kVariable05, "Variable05" },
	{ RE::ActorValue::kVariable06, "Variable06" },
	{ RE::ActorValue::kVariable07, "Variable07" },
	{ RE::ActorValue::kVariable08, "Variable08" },
	{ RE::ActorValue::kVariable09, "Variable09" },
	{ RE::ActorValue::kVariable10, "Variable10" },
	{ RE::ActorValue::kBowSpeedBonus, "BowSpeedBonus" },
	{ RE::ActorValue::kFavorActive, "FavorActive" },
	{ RE::ActorValue::kFavorsPerDay, "FavorsPerDay" },
	{ RE::ActorValue::kFavorsPerDayTimer, "FavorsPerDayTimer" },
	{ RE::ActorValue::kLeftItemCharge, "LeftItemCharge" },
	{ RE::ActorValue::kAbsorbChance, "AbsorbChance" },
	{ RE::ActorValue::kBlindness, "Blindness" },
	{ RE::ActorValue::kWeaponSpeedMult, "WeaponSpeedMult" },
	{ RE::ActorValue::kShoutRecoveryMult, "ShoutRecoveryMult" },
	{ RE::ActorValue::kBowStaggerBonus, "BowStaggerBonus" },
	{ RE::ActorValue::kTelekinesis, "Telekinesis" },
	{ RE::ActorValue::kFavorPointsBonus, "FavorPointsBonus" },
	{ RE::ActorValue::kLastBribedIntimidated, "LastBribedIntimidated" },
	{ RE::ActorValue::kLastFlattered, "LastFlattered" },
	{ RE::ActorValue::kMovementNoiseMult, "MovementNoiseMult" },
	{ RE::ActorValue::kBypassVendorStolenCheck, "BypassVendorStolenCheck" },
	{ RE::ActorValue::kBypassVendorKeywordCheck, "BypassVendorKeywordCheck" },
	{ RE::ActorValue::kWaitingForPlayer, "WaitingForPlayer" },
	{ RE::ActorValue::kOneHandedModifier, "OneHandedModifier" },
	{ RE::ActorValue::kTwoHandedModifier, "TwoHandedModifier" },
	{ RE::ActorValue::kMarksmanModifier, "MarksmanModifier" },
	{ RE::ActorValue::kBlockModifier, "BlockModifier" },
	{ RE::ActorValue::kSmithingModifier, "SmithingModifier" },
	{ RE::ActorValue::kHeavyArmorModifier, "HeavyArmorModifier" },
	{ RE::ActorValue::kLightArmorModifier, "LightArmorModifier" },
	{ RE::ActorValue::kPickpocketModifier, "PickpocketModifier" },
	{ RE::ActorValue::kLockpickingModifier, "LockpickingModifier" },
	{ RE::ActorValue::kSneakingModifier, "SneakingModifier" },
	{ RE::ActorValue::kAlchemyModifier, "AlchemyModifier" },
	{ RE::ActorValue::kSpeechcraftModifier, "SpeechcraftModifier" },
	{ RE::ActorValue::kAlterationModifier, "AlterationModifier" },
	{ RE::ActorValue::kConjurationModifier, "ConjurationModifier" },
	{ RE::ActorValue::kDestructionModifier, "DestructionModifier" },
	{ RE::ActorValue::kIllusionModifier, "IllusionModifier" },
	{ RE::ActorValue::kRestorationModifier, "RestorationModifier" },
	{ RE::ActorValue::kEnchantingModifier, "EnchantingModifier" },
	{ RE::ActorValue::kOneHandedSkillAdvance, "OneHandedSkillAdvance" },
	{ RE::ActorValue::kTwoHandedSkillAdvance, "TwoHandedSkillAdvance" },
	{ RE::ActorValue::kMarksmanSkillAdvance, "MarksmanSkillAdvance" },
	{ RE::ActorValue::kBlockSkillAdvance, "BlockSkillAdvance" },
	{ RE::ActorValue::kSmithingSkillAdvance, "SmithingSkillAdvance" },
	{ RE::ActorValue::kHeavyArmorSkillAdvance, "HeavyArmorSkillAdvance" },
	{ RE::ActorValue::kLightArmorSkillAdvance, "LightArmorSkillAdvance" },
	{ RE::ActorValue::kPickpocketSkillAdvance, "PickpocketSkillAdvance" },
	{ RE::ActorValue::kLockpickingSkillAdvance, "LockpickingSkillAdvance" },
	{ RE::ActorValue::kSneakingSkillAdvance, "SneakingSkillAdvance" },
	{ RE::ActorValue::kAlchemySkillAdvance, "AlchemySkillAdvance" },
	{ RE::ActorValue::kSpeechcraftSkillAdvance, "SpeechcraftSkillAdvance" },
	{ RE::ActorValue::kAlterationSkillAdvance, "AlterationSkillAdvance" },
	{ RE::ActorValue::kConjurationSkillAdvance, "ConjurationSkillAdvance" },
	{ RE::ActorValue::kDestructionSkillAdvance, "DestructionSkillAdvance" },
	{ RE::ActorValue::kIllusionSkillAdvance, "IllusionSkillAdvance" },
	{ RE::ActorValue::kRestorationSkillAdvance, "RestorationSkillAdvance" },
	{ RE::ActorValue::kEnchantingSkillAdvance, "EnchantingSkillAdvance" },
	{ RE::ActorValue::kLeftWeaponSpeedMultiply, "LeftWeaponSpeedMultiply" },
	{ RE::ActorValue::kDragonSouls, "DragonSouls" },
	{ RE::ActorValue::kCombatHealthRegenMultiply, "CombatHealthRegenMultiply" },
	{ RE::ActorValue::kOneHandedPowerModifier, "OneHandedPowerModifier" },
	{ RE::ActorValue::kTwoHandedPowerModifier, "TwoHandedPowerModifier" },
	{ RE::ActorValue::kMarksmanPowerModifier, "MarksmanPowerModifier" },
	{ RE::ActorValue::kBlockPowerModifier, "BlockPowerModifier" },
	{ RE::ActorValue::kSmithingPowerModifier, "SmithingPowerModifier" },
	{ RE::ActorValue::kHeavyArmorPowerModifier, "HeavyArmorPowerModifier" },
	{ RE::ActorValue::kLightArmorPowerModifier, "LightArmorPowerModifier" },
	{ RE::ActorValue::kPickpocketPowerModifier, "PickpocketPowerModifier" },
	{ RE::ActorValue::kLockpickingPowerModifier, "LockpickingPowerModifier" },
	{ RE::ActorValue::kSneakingPowerModifier, "SneakingPowerModifier" },
	{ RE::ActorValue::kAlchemyPowerModifier, "AlchemyPowerModifier" },
	{ RE::ActorValue::kSpeechcraftPowerModifier, "SpeechcraftPowerModifier" },
	{ RE::ActorValue::kAlterationPowerModifier, "AlterationPowerModifier" },
	{ RE::ActorValue::kConjurationPowerModifier, "ConjurationPowerModifier" },
	{ RE::ActorValue::kDestructionPowerModifier, "DestructionPowerModifier" },
	{ RE::ActorValue::kIllusionPowerModifier, "IllusionPowerModifier" },
	{ RE::ActorValue::kRestorationPowerModifier, "RestorationPowerModifier" },
	{ RE::ActorValue::kEnchantingPowerModifier, "EnchantingPowerModifier" },
	{ RE::ActorValue::kDragonRend, "DragonRend" },
	{ RE::ActorValue::kAttackDamageMult, "AttackDamageMult" },
	{ RE::ActorValue::kHealRateMult, "HealRateMult" },
	{ RE::ActorValue::kMagickaRateMult, "MagickaRateMult" },
	{ RE::ActorValue::kStaminaRateMult, "StaminaRateMult" },
	{ RE::ActorValue::kWerewolfPerks, "WerewolfPerks" },
	{ RE::ActorValue::kVampirePerks, "VampirePerks" },
	{ RE::ActorValue::kGrabActorOffset, "GrabActorOffset" },
	{ RE::ActorValue::kGrabbed, "Grabbed" },
	{ RE::ActorValue::kUnknown162, "DEPRECATED05" },
	{ RE::ActorValue::kReflectDamage, "ReflectDamage" }
};

namespace ActorValueHelper
{
	auto StringToActorValue(const RE::BSFixedString& a_string) -> RE::ActorValue {
		auto av = find_if(ACTOR_VALUES.begin(), ACTOR_VALUES.end(), [a_string](auto const& pr) {
			return pr.second == a_string;
		});

		if (av != ACTOR_VALUES.end()) {
			return av->first;
		} else {
			return RE::ActorValue::kNone;
		}
	}

	auto ActorValueToString(const RE::ActorValue a_actorValue) -> RE::BSFixedString
	{
		return ACTOR_VALUES.at(a_actorValue);
	}
}